version: '3.8'

services:
  stockapp:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "80:8080"
      - "443:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MARKETSTACK_API_KEY=83c8eb73c602dc78f07f9235123411b4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
