apiVersion: v1
kind: ConfigMap
metadata:
  name: stockapp-config
data:
  SPRING_PROFILES_ACTIVE: "prod"
  MARKETSTACK_API_KEY: "83c8eb73c602dc78f07f9235123411b4"
  MARKETSTACK_API_URL: "https://api.marketstack.com/v2"
