apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockapp-backend
  labels:
    app: stockapp-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stockapp-backend
  template:
    metadata:
      labels:
        app: stockapp-backend
    spec:
      containers:
      - name: stockapp-backend
        image: 481665085747.dkr.ecr.us-east-2.amazonaws.com/stockapp-backend:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: stockapp-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
